# Generated by Django 5.2.6 on 2025-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
