# Generated by Django 5.2.6 on 2025-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamification",
            "0003_category_puzzle_quizquestion_puzzleoption_quizoption_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=7,
            ),
        ),
    ]
