# Generated by Django 5.2.6 on 2025-09-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0004_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=7,
            ),
        ),
    ]
