# Generated by Django 5.2.6 on 2025-09-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0005_remove_user_gender_studentprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksubmission",
            name="game",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"game_type": "real_world_task"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamification.game",
            ),
        ),
    ]
