# Generated by Django 5.2.6 on 2025-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0006_alter_tasksubmission_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecopoint",
            name="is_daily",
            field=models.BooleanField(default=False),
        ),
    ]
