# Generated by Django 5.2.6 on 2025-09-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0007_ecopoint_is_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecopoint",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamification.tasksubmission",
            ),
        ),
    ]
